### PR TITLE
Switch to v3 onions where possible

### PR DESCRIPTION
**Pull request by herypt**
Propublica automatically redirects to the v3 onion, Torstatus shows it on the homepage, systemli shows ".onion available" when visiting the clearnet site and the riseup domains are listed [here](https://riseup.net/en/security/network-security/tor)

### CODE REVIEW

**Comment by adrelanos** [comment]
https://forums.whonix.org/t/suggest-trustworthy-tor-hidden-services-as-time-sources-for-sdwdate/856/151

**Review by adrelanos — CHANGES_REQUESTED** [review]
Thank you for working on this!

Comments need to be updated too. The comment field is used to proof that the onion domain name is correct. Example...

currently:

             "propub3r6espa33w.onion#https://www.propublica.org/nerds/item/a-more-secure-and-anonymous-propublica-using-tor-hidden-services	https://web.archive.org/web/20170420120434/https://www.propublica.org/nerds/item/a-more-secure-and-anonymous-propublica-using-tor-hidden-services" 

suggested in your pull request:

             "p53lf57qovyuvwsc6xnrppyply3vtqm7l6pcobkmyqsiofyeznfu5uqd.onion#https://www.propublica.org/nerds/item/a-more-secure-and-anonymous-propublica-using-tor-hidden-services	https://web.archive.org/web/20170420120434/https://www.propublica.org/nerds/item/a-more-secure-and-anonymous-propublica-using-tor-hidden-services" 

But the comment (`https://www.propublica.org/nerds/item/a-more-secure-and-anonymous-propublica-using-tor-hidden-services	https://web.archive.org/web/20170420120434/https://www.propublica.org/nerds/item/a-more-secure-and-anonymous-propublica-using-tor-hidden-services`) does not contain `p53lf57qovyuvwsc6xnrppyply3vtqm7l6pcobkmyqsiofyeznfu5uqd.onion`.

Could you please update the comments too?

**Comment by herypt** [comment]
Done, couldn't find proof other than the Onion-Location header for Propublica though.

**Comment by adrelanos** [comment]
Awesome! Thanks! Please keep it coming.
As for cases of having only `Onion-Location header`, I guess this will be more and more the case in future. In that case, I guess we don't have much choice. But at least we can use https://securityheaders.com. Example:

* https://securityheaders.com/?q=https%3A%2F%2Fwww.propublica.org&followRedirects=off
* https://web.archive.org/web/20200905091808/https://securityheaders.com/?q=https%3A%2F%2Fwww.propublica.org&followRedirects=off

Will add propublica comment in git master now.

**Pull request merged**
